---

- name: "[Cleanup - {{item}}]: Remove meta-data file"
  file:
    path: "/tmp/{{item}}"
    state: absent

- name: "[Cleanup - {{item}}]: Detach the ISO"
  command: "virsh change-media {{item}} sda --eject --config --live"
  register: iso_ejected
  ignore_errors: true
  changed_when:
    - '"error" in iso_ejected.stderr'
    - iso_ejected.rc == 1

- set_fact:
    CURRENT_HOST: "{{item}}"

- name: "[Cleanup - {{item}}]: Remove all files"
  file:
    path: "{{item}}"
    state: absent
  with_fileglob:
    - "{{LIBVIRT_IMAGES}}/builds/*"