---

- name: "[Firewall]: Enable firewall rules"
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
    zone: public
  with_items:
    - 6443/tcp
    - 8404/tcp
  tags:
    - install_haproxy

- name: "[Firewall]: Restart firewall"
  systemd:
    name: firewalld
    state: restarted