---

- include: 100_install_packages.yml
  tags:
    - install_haproxy

- include: 101_configs.yml
  tags:
    - install_haproxy

- include: 102_network.yml
  tags:
    - install_haproxy

- include: 103_firewall.yml
  tags:
    - install_haproxy

- include: 104_init.yml
  tags:
    - install_haproxy