---

- include: 104_4_install_cfssl.yml
  tags: install_cfssl

- name: "[Add SSL]: Make SSL directories"
  file:
    path: "{{PKI_DIR}}/{{item}}"
    state: directory
    recurse: yes
    owner: "{{LOCAL_USER}}"
    group: "{{LOCAL_USER}}"
    mode: '0755'
  with_items:
    - tiller-ca
    - tiller-host
    - helm-user

- name: "[Add SSL]: Copy SSL CA config"
  copy:
    src: tiller-ca-config.json
    dest: "{{PKI_DIR}}/tiller-ca/tiller-ca-config.json"

- name: "[Add SSL]: Generate the Tiller CA csr config file"
  template:
    src: tiller-ca-csr.json.j2
    dest: "{{PKI_DIR}}/tiller-ca/ca-csr.json"

- name: "[Add SSL]: Generate the Tiller CA certificates"
  shell: "cfssl gencert -initca {{PKI_DIR}}/tiller-ca/ca-csr.json | cfssljson -bare {{PKI_DIR}}/tiller-ca/ca"

- name: "[Add SSL]: Generate the Tiller host csr config file"
  template:
    src: tiller-host-csr.json.j2
    dest: "{{PKI_DIR}}/tiller-host/tiller-host-csr.json"

- name: "[Add SSL]: Generate the Tiller host certificates"
  shell: "cfssl gencert \
    -ca={{PKI_DIR}}/tiller-ca/ca.pem \
    -ca-key={{PKI_DIR}}/tiller-ca/ca-key.pem \
    -config={{PKI_DIR}}/tiller-ca/tiller-ca-config.json \
    -hostname=127.0.0.1,tiller-server \
    -profile=tiller \
    {{PKI_DIR}}/tiller-host/tiller-host-csr.json | cfssljson -bare {{PKI_DIR}}/tiller-host/tiller-host"

- name: "[Add SSL]: Generate the Helm users csr config file"
  template:
    src: helm-user-csr.json.j2
    dest: "{{PKI_DIR}}/helm-user/helm-user-csr.json"

- name: "[Add SSL]: Generate the Helm user certificates"
  shell: "cfssl gencert \
    -ca={{PKI_DIR}}/tiller-ca/ca.pem \
    -ca-key={{PKI_DIR}}/tiller-ca/ca-key.pem \
    -config={{PKI_DIR}}/tiller-ca/tiller-ca-config.json \
    -profile=tiller \
    {{PKI_DIR}}/helm-user/helm-user-csr.json | cfssljson -bare {{PKI_DIR}}/helm-user/helm-user"

- name: "[Add SSL]: Make helm directory in home"
  file:
    path: "/home/{{LOCAL_USER}}/.helm/"
    state: directory
    recurse: yes
    owner: "{{LOCAL_USER}}"
    group: "{{LOCAL_USER}}"
    mode: '0755'

- name: "[Add SSL]: Copy SSL CA key for helm"
  copy:
    src: "{{PKI_DIR}}/tiller-ca/ca.pem"
    dest: "/home/{{LOCAL_USER}}/.helm/ca.pem"

- name: "[Add SSL]: Copy SSL user cert for helm"
  copy:
    src: "{{PKI_DIR}}/helm-user/helm-user.pem"
    dest: "/home/{{LOCAL_USER}}/.helm/cert.pem"

- name: "[Add SSL]: Copy SSL user key for helm"
  copy:
    src: "{{PKI_DIR}}/helm-user/helm-user-key.pem"
    dest: "/home/{{LOCAL_USER}}/.helm/key.pem"