---

- name: "[Init]: Initialise helm"
  command: "/usr/local/bin/helm init \
  --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
  --service-account=tiller \
  --tiller-namespace={{item}} \
  --history-max=200 \
  --tiller-tls \
  --tiller-tls-verify \
  --tiller-tls-cert={{PKI_DIR}}/tiller-host/tiller-host.pem \
  --tiller-tls-key={{PKI_DIR}}/tiller-host/tiller-host-key.pem \
  --tls-ca-cert={{PKI_DIR}}/tiller-ca/ca.pem"
  with_items: "{{TILLER_NAMESPACES}}"

- name: "[Init]: Tiller can take 1-2 minutes to come up, waiting for 120 seconds..."
  pause:
    seconds: 120

- name: "[Init]: Checking tiller state"
  command: "kubectl -n {{item}} get deployment tiller-deploy"
  with_items: "{{TILLER_NAMESPACES}}"

- name: "[Init]: Checking helm commands work"
  command: "helm ls \
  --tls \
  --tls-verify \
  --tls-cert=/home/{{LOCAL_USER}}/.helm/cert.pem \
  --tls-key=/home/{{LOCAL_USER}}/.helm/key.pem \
  --tls-ca-cert=/home/{{LOCAL_USER}}/.helm/ca.pem \
  --tiller-namespace={{item}}"
  with_items: "{{TILLER_NAMESPACES}}"