---

#- name: "[Add SSL]: Check for the Tiller host certificates for {{item}}"
#  stat:
#    path: "{{PKI_DIR}}/tiller-host/{{item}}/tiller-host-key.pem"
#  register: certs_gen
#
#- name: "[Add SSL]: Generate the Tiller host certificates for {{item}}"
#  shell: "cfssl gencert \
#    -ca={{PKI_DIR}}/tiller-ca/ca.pem \
#    -ca-key={{PKI_DIR}}/tiller-ca/ca-key.pem \
#    -config={{PKI_DIR}}/tiller-ca/tiller-ca-config.json \
#    -hostname=127.0.0.1,tiller-server \
#    -profile=tiller \
#    {{PKI_DIR}}/tiller-host/tiller-host-csr.json | cfssljson -bare {{PKI_DIR}}/tiller-host/{{item}}/tiller-host"
#  when: certs_gen.stat.exists is defined and not certs_gen.stat.exists

- name: "[Add SSL]: Check for the Tiller host certificate"
  stat:
    path: "{{PKI_DIR}}/tiller-host/kube-system/tiller-host-key.pem"
  register: certs_gen

- name: "[Add SSL]: Generate the Tiller host certificate"
  shell: "cfssl gencert \
    -ca={{PKI_DIR}}/tiller-ca/ca.pem \
    -ca-key={{PKI_DIR}}/tiller-ca/ca-key.pem \
    -config={{PKI_DIR}}/tiller-ca/tiller-ca-config.json \
    -hostname=127.0.0.1,tiller-server \
    -profile=tiller \
    {{PKI_DIR}}/tiller-host/tiller-host-csr.json | cfssljson -bare {{PKI_DIR}}/tiller-host/kube-system/tiller-host"
  when: certs_gen.stat.exists is defined and not certs_gen.stat.exists