---

- include: 101_fetch_helm.yml
  tags:
    - install_helm
    - fetch_helm

# -- IF YOU REALLY WANT TO ENABLE TILLER UNCOMMENT ALL OF THE BELOW, BUT DON'T CAUSE THAT'S SILLY. --

- include: 102_namespaces.yml
  tags:
    - install_helm
    - tiller_namespace

- include: 103_add_rbac.yml
  tags:
    - install_helm
    - helm_rbac

- include: 104_add_ssl.yml
  tags:
    - install_helm
    - helm_ssl

- include: 105_init.yml
  tags:
    - install_helm
    - helm_init
    - install_tiller
