---

- name: "[Config]: Make directories"
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'
  with_items:
    - "/var/log/kubernetes"
    - "/etc/kubernetes/manifests"
    - "/etc/kubernetes/policies"

- name: "[Init]: Copy kubernetes policies"
  copy:
    src: "policies/audit-policy.yaml"
    dest: "/etc/kubernetes/policies/audit-policy.yaml"