---

- name: "[Add Nodes]: Copy Join Token to worker node"
  copy:
    src: "{{KUBE_ADM_TOKEN_DIR}}/node_token"
    dest: /tmp/node_token
  tags:
    - kubeadm_node

# If this fails it is very likely it's because of expired certs.
# For new cert key go to active controller and run: sudo kubeadm init phase upload-certs --upload-certs
# TODO: Needs ansible block really to do this for the user - wouldn't that be friendly and helpful?
- name: "[Add Nodes]: Join worker nodes to cluster"
  shell: "$(cat /tmp/node_token)"
  register: kubeadm_join_node
  tags:
    - kubeadm_node

#- name: "[Init]: Waiting for Ready state"
#  waitfor:
#    command: "kubectl get nodes -o json | jq -Mr '[.items[] | {name: .metadata.name, status: .status.conditions[].type}]' | jq -Mr '.[] | select(.name == \"{{inventory_hostname}}\" and .status == \"Ready\")'"
#  when: kubeadm_init