---

- name: "[init]: Check for StorageOS CRDs"
  shell: "kubectl get crds --kubeconfig /home/{{LOCAL_USER}}/.kube/config"
  delegate_to: localhost
  run_once: true
  register: storage_crds_check
  tags:
    - install_storageos

- name: "[init]: Install StorageOS Operator onto K8S"
  command: "kubectl create -f /tmp/storageos-operator.yml --kubeconfig /home/{{LOCAL_USER}}/.kube/config"
  delegate_to: localhost
  run_once: true
  when: storage_crds_check.stdout_lines|length == 0
  tags:
    - install_storageos

- name: "[init]: StorageOS Operator can take a few seconds to come up..."
  pause:
    seconds: 10
  delegate_to: localhost
  when: storage_crds_check.stdout_lines|length == 0
  tags:
    - install_storageos

- name: "[init]: Check for StorageOS Secrets"
  shell: "kubectl get secrets -n storageos-operator --kubeconfig /home/{{LOCAL_USER}}/.kube/config"
  delegate_to: localhost
  run_once: true
  register: storage_secret_check
  changed_when: storage_secret_check.stdout_lines|length == 0
  tags:
    - install_storageos

- name: "[init]: Install StorageOS secret onto K8S"
  command: "kubectl create -f /tmp/storageos-secret.yml --kubeconfig /home/{{LOCAL_USER}}/.kube/config"
  delegate_to: localhost
  run_once: true
  when: "'storageos-api' not in storage_secret_check.stdout"
  tags:
    - install_storageos

- name: "[init]: Check for StorageOS Install"
  shell: "kubectl get StorageOSCluster -n storageos-operator --kubeconfig /home/{{LOCAL_USER}}/.kube/config"
  delegate_to: localhost
  run_once: true
  register: storage_install_check
  changed_when: storage_install_check.stdout_lines|length == 0
  tags:
    - install_storageos

- name: "[init]: Install StorageOS onto K8S"
  command: "kubectl create -f /tmp/storageos-install.yml --kubeconfig /home/{{LOCAL_USER}}/.kube/config"
  delegate_to: localhost
  run_once: true
  when: storage_install_check.stdout_lines|length == 0
  tags:
    - install_storageos

- name: "[init]: StorageOS can take around 65 seconds to come up, waiting for 80 seconds..."
  pause:
    seconds: 80
  delegate_to: localhost
  tags:
    - install_storageos