---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-plugins-pvc
  namespace: monitoring
spec:
  storageClassName: "permanent"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi