---

- name: "[APT]: Install nfs packages"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - nfs-kernel-server
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "[YUM]: Install nfs packages"
  yum:
    name:
      - nfs-utils
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
