---

- name: "[Firewall]: Disable package"
  yum:
    name: firewalld
  tags:
    - firewall

- name: "[Firewall]: Stop Firewall"
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  tags:
    - firewall

#- include: 100_packages.yml
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
#  tags:
#    - firewall
#
#- include: 101_firewalld_configuration.yml
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
#  tags:
#    - firewall