---

- name: "[Install Packages - Ansible]: Install YUM specific packages"
  yum:
    name: kubectl
    state: present
    disable_excludes: kubernetes
  register: package_res
  retries: 10
  until: package_res is success
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "[Install Packages - Ansible]: Hold back packages from auto upgrades"
  dpkg_selections:
    name: "{{item}}"
    selection: hold
  with_items:
    - kubectl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "[Install Packages - Ansible]: Install APT specific packages"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  register: package_res
  retries: 10
  until: package_res is success
  vars:
    packages:
      - kubectl
      - python-docker
      - python-libvirt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'