---

- name: "[Docker - Daemon]: Copy the demon config over"
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0644'
  register: docker_
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "[Docker]: Make directories"
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes
  tags:
    - install_docker

- name: "[Docker - Daemon]: Make sure docker is Started"
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes