---

- name: "[Docker]: Make directories"
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes
  tags:
    - install_docker

- include: 101_yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - install_docker

- include: 100_apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - install_docker

- include: 102_update_daemon.yml
  tags:
    - install_docker